### ISSUE TITLE
Annotation on Video Call

### ISSUE THREAD

**Issue by rosygupta** [opentok/accelerator-annotation-js#41]
I have read all of the [`README`](../README.md) 
- I have searched [existing issues](https://github.com/opentok/accelerator-annotation-js/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## Bug report
There is no documentation of how to implement annotation on a video call but this blog reports this feature.
https://tokbox.com/blog/introducing-the-annotation-widget-in-beta/
This is more like a feature request if not available.

**Comment by rosygupta** [comment]
@maikthomas  Can you please help here?

**Comment by maikthomas** [comment]
Hi @rosygupta I'm looking into this, I'll get back to you as soon as I have an answer!
Thanks,
Mike

**Comment by msach22** [comment]
Hey @rosygupta Unfortunately, we don't have any documentation on implementing annotations on a video call. We've classified the annotation widget as an OpenTok Labs project because TokBox does not officially support this repo.

**Comment by priyasamyal** [comment]
does someone how to implement it

**Comment by RamyaAshika** [comment]
Did you got any documentation for this @rosygupta

**Comment by rosygupta** [comment]
@RamyaAshika please read the contributors comment above.

**Comment by RamyaAshika** [comment]
ooh fine, but is it possible to add annotation in the video call? I'm struggling for this a week. Do you get any solution for this? @rosygupta
