### ISSUE TITLE
There is no documentation of how to implement annotation on a video call in java script.

### ISSUE THREAD

**Issue by lntserviceiq5** [opentok/accelerator-annotation-js#44]
Hi,
I am trying to implement annotation on a video call using https://github.com/opentok/accelerator-annotation-js but i am not able to proceed. i am trying to run the sample that is also not happening.. can somebody help me on this.

**Comment by byronCoetzee** [comment]
no answer  thanks vonage - this is unprofessional. You have  blog post touting this, but very little on how to use this.
video and screen sharing annoations are important - especially in etutoring

**Comment by masakinpo** [comment]
@byronCoetzee 
cloud you kindly share the blog post regarding the annotation feature?

**Comment by MichaelJolley** [comment]
Hi @lntserviceiq5. Are you using the accelerator-annotation-js with the accelerator-core-js?

**Comment by MichaelJolley** [comment]
Closing due to staleness
