### ISSUE TITLE
Opentok @ Why isn't they a practical documentation for the opentok annotation?

### ISSUE THREAD

**Issue by anthonylan** [opentok/accelerator-annotation-js#45]
## New issue checklist

- [ ] I have read all of the [`README`](../README.md) 
- [ ] I have searched [existing issues](https://github.com/opentok/accelerator-annotation-js/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by byronCoetzee** [comment]
I agree this is terrible documentation - not everyone is an expert in javascript.
How about a little help getting people to use this....

**Comment by MichaelJolley** [comment]
Hi @anthonylan, The `accelerator-annotation-js` library is meant to be used with [`accelerator-core-js`](https://github.com/opentok/accelerator-core-js) library. It is an add-on to that library.  Are you using it in that manner or with a normal OpenTok client using our SDKs?

**Comment by MichaelJolley** [comment]
Closing due to staleness.
